name: Deployment

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Load and cache dependencies
        uses: ./angular-app/.github/actions/cached_deps

      - name: Lint code
        run: npm run lint --prefix angular-app

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Load and cache dependencies
        uses: ./angular-app/.github/actions/cached_deps

      - name: Test code
        id: run-tests
        run: npm run test --prefix angular-app

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: angular-app/test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --prefix angular-app

      - name: Build website
        run: npm run build --prefix angular-app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: angular-app/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: angular-app/dist

      - name: Output contents
        run: ls -l angular-app/dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Change this if your bucket is in a different region

      - name: Deploy site
        id: deploy
        uses: ./angular-app/.github/actions/deployment
        with:
          bucketName: myangular-dep
          distFiles: angular-app/dist

      - name: Output deployment link
        run: echo "Deployed URL: ${{ steps.deploy.outputs.URL }}"
